/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 16 18:18:12 GMT 2025
 */

package maven;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import maven.Money;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Money_ESTest extends Money_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Money money0 = new Money((-1), "'?p");
      Money money1 = new Money(1, "'?p");
      boolean boolean0 = money0.equals(money1);
      assertEquals(1, money1.getAmount());
      assertFalse(money1.equals((Object)money0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Money money0 = new Money((-1), (String) null);
      money0.getCurrency();
      assertEquals((-1), money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Money money0 = new Money(0, "8<\"UmaBD");
      money0.getCurrency();
      assertEquals(0, money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Money money0 = new Money((-1), "'?p");
      Money money1 = new Money(1, "'?p");
      Money money2 = money1.add(money0);
      Money money3 = money2.add(money1);
      Money money4 = money0.add(money3);
      int int0 = money4.getAmount();
      assertEquals(0, int0);
      assertFalse(money3.equals((Object)money2));
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Money money0 = new Money(383, "Dc=>vE'%3M!S[3GTNi");
      int int0 = money0.getAmount();
      assertEquals(383, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Money money0 = new Money(729, (String) null);
      Money money1 = new Money(0, (String) null);
      Money money2 = money0.add(money1);
      // Undeclared exception!
      try { 
        money0.equals(money2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Money money0 = new Money((-1983), "");
      // Undeclared exception!
      try { 
        money0.add((Money) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("maven.Money", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Money money0 = new Money(0, "");
      money0.getCurrency();
      assertEquals(0, money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Money money0 = new Money((-937), "-");
      Money money1 = new Money((-937), ",");
      boolean boolean0 = money1.equals(money0);
      assertEquals((-937), money1.getAmount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Money money0 = new Money((-4083), "<8");
      Money money1 = money0.add(money0);
      boolean boolean0 = money0.equals(money1);
      assertEquals((-8166), money1.getAmount());
      assertFalse(money1.equals((Object)money0));
      assertFalse(boolean0);
      assertEquals((-4083), money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Money money0 = new Money((-937), "-");
      boolean boolean0 = money0.equals("-");
      assertFalse(boolean0);
      assertEquals((-937), money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Money money0 = new Money((-4083), "<8");
      boolean boolean0 = money0.equals(money0);
      assertEquals((-4083), money0.getAmount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Money money0 = new Money((-1983), "");
      int int0 = money0.getAmount();
      assertEquals((-1983), int0);
  }
}
